# -*- coding: utf-8 -*-
"""torch.nn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1izAvOKV6Gh0FZJhyt3wFIEgUdqTQZ4cA
"""

import torch
import torch.nn as nn

model = nn.Sequential(
    nn.Linear(2, 4),
    nn.ReLU(),
    nn.Linear(4, 1)
)

x = torch.tensor([[0.,0.],[0.,1.],[1.,0.],[1.,1.]])
y = torch.tensor([[0.],[1.],[1.],[0.]])

loss_fn = nn.MSELoss()
opt = torch.optim.SGD(model.parameters(), lr=0.01)

for _ in range(1000):
  opt.zero_grad()
  loss = loss_fn(model(x), y)
  loss.backward()
  opt.step()

print(model(x))

pip install google-genai

from google import genai

from google import genai
lient = genai.Client(api_key='AIzaSyBF6oeJWCovxLK31RN-gMOF2oB2a8SEUjU')

response = client.models.generate_content(
    model='gemini-2.5-flash',
    contents='Why is the sky blue?'
).text
print(response)